In [15]:
import json
import pandas as pd

In [3]:
with open('../data/raw/matches_20260512_085115.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [80]:
partidos = list()

for match in data:
    partidos.append({
        "match_id": match['id'],
        "country": match['area']['name'],
        "competition": match['competition']['name'],
        "utc_date": match['utcDate'],
        "status": match['status'],
        "season": f"{match['season']['startDate'][:4]} - {match['season']['endDate'][:4]}",
        "matchday": match['matchday'],
        "home_team": match['homeTeam']['name'],
        "away_team": match['awayTeam']['name'],
        "home_goals": match['score']['fullTime']['home'],
        "away_goals": match['score']['fullTime']['away'],
        "winner": match['score']['winner'],
        "referee": match['referees'][0]['name'] if match['referees'] else "Desconocido"
    })

In [87]:
df = pd.DataFrame(partidos)

# Partidos finalizados
df_new = df.loc[df["status"] == 'FINISHED']
df_new["home_goals"] = df_new["home_goals"].astype(int)
df_new["away_goals"] = df_new["away_goals"].astype(int)
df_new["utc_date"] = pd.to_datetime(df_new["utc_date"])

In [88]:
df_new.head()

,match_id,country,competition,utc_date,status,season,matchday,home_team,away_team,home_goals,away_goals,winner,referee
0,544214,Spain,Primera Division,2025-08-15 17:00:00+00:00,FINISHED,2025 - 2026,1,Girona FC,Rayo Vallecano de Madrid,1,3,AWAY_TEAM,Javier Alberola Rojas
1,544220,Spain,Primera Division,2025-08-15 19:30:00+00:00,FINISHED,2025 - 2026,1,Villarreal CF,Real Oviedo,2,0,HOME_TEAM,Alejandro Muñiz Ruiz
2,544216,Spain,Primera Division,2025-08-16 17:30:00+00:00,FINISHED,2025 - 2026,1,RCD Mallorca,FC Barcelona,0,3,AWAY_TEAM,José Munuera Montero
3,544211,Spain,Primera Division,2025-08-16 19:30:00+00:00,FINISHED,2025 - 2026,1,Deportivo Alavés,Levante UD,2,1,HOME_TEAM,Miguel Sesma Espinosa
4,544219,Spain,Primera Division,2025-08-16 19:30:00+00:00,FINISHED,2025 - 2026,1,Valencia CF,Real Sociedad de Fútbol,1,1,DRAW,José Sánchez Martínez

In [66]:
import numpy as np

In [89]:
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   match_id     350 non-null    int64
 1   country      350 non-null    str
 2   competition  350 non-null    str
 3   utc_date     350 non-null    datetime64[us, UTC]
 4   status       350 non-null    str
 5   season       350 non-null    str
 6   matchday     350 non-null    int64
 7   home_team    350 non-null    str
 8   away_team    350 non-null    str
 9   home_goals   350 non-null    int64
 10  away_goals   350 non-null    int64
 11  winner       350 non-null    str
 12  referee      350 non-null    str
dtypes: datetime64[us, UTC](1), int64(4), str(8)
memory usage: 35.7 KB

In [84]:
df_new.describe()

            match_id    matchday  home_goals  away_goals
count     350.000000  350.000000  350.000000  350.000000
mean   544385.500000   18.000000    1.557143    1.128571
std       101.180532   10.113964    1.199758    0.971240
min    544211.000000    1.000000    0.000000    0.000000
25%    544298.250000    9.000000    1.000000    0.000000
50%    544385.500000   18.000000    1.000000    1.000000
75%    544472.750000   27.000000    2.000000    2.000000
max    544560.000000   35.000000    6.000000    5.000000

In [85]:
# Valores infinitos (?)
df_new.isin([np.inf, -np.inf]).any()

match_id       False
country        False
competition    False
utc_date       False
status         False
season         False
matchday       False
home_team      False
away_team      False
home_goals     False
away_goals     False
winner         False
referee        False
dtype: bool

In [86]:
# Valores nulos
df_new.isnull().sum()

match_id       0
country        0
competition    0
utc_date       0
status         0
season         0
matchday       0
home_team      0
away_team      0
home_goals     0
away_goals     0
winner         0
referee        0
dtype: int64

In [90]:
df_new.to_csv('../data/processed/laliga_matches.csv', index=False)